### ISSUE TITLE
tactile_mapping not defined

### ISSUE THREAD

**Issue by parrajeremy** [ubi-agni/human_hand#1]
Indigo on ubuntu 14.04

@ubuntu:~/catkin_ws$ roslaunch human_hand_description display.launch
... logging to /home/<user>/.ros/log/d38c997a-43d8-11e6-98e2-000c29d553a5/roslaunch-ubuntu-4930.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

arg 'tactile_mapping' is not defined. 

Arg xml is <arg name="tactile_mapping" value="$(arg tactile_mapping)"/>
The traceback for the exception was written to the log file

[roslaunch-ubuntu-5136.txt](https://github.com/ubi-agni/human_hand/files/351160/roslaunch-ubuntu-5136.txt)

**Comment by rhaschke** [comment]
Sorry. The `tactile_mapping` argument became mandatory meanwhile. I've updated the readme.
