### ISSUE TITLE
Palm taxel centers of L3left not matching L3right

### ISSUE THREAD

**Issue by guihomework** [ubi-agni/human_hand#10]
To produce left and right hands, we use right taxel meshes (for instance ptmp.stl) and apply an x axis mirror operation to the meshes in URDF
However due to more complex problem of RPY angles "flip" using limited xacro python capabilities, there is no such operation done for taxel normals (stored in the yaml files). Hence there are 2 files containing the left and right taxels normals AND their centers (for instance L3left.yaml and L3right.yaml).
To produce those 2 files one uses 2 Blender models that have been manually mirrored and apply a script extracting the centers and normals.

There is a bug in the mirror in the Blender models. For some reason the left L3 palm meshes were not mirrored through the 0 of x axis but through the 2mm of x axis, creating a shift of the left model around 4 mm to the side. Then all L3left palm taxels centers were shifted as well creating wrong centers.

This was not seen before because taxels centers were "somewhere" inside the hand (due to their curvature), or not easily humanly visible due to the complex shape of the palm taxels (vs easy squarish form of the finger taxels) that does not make the shift obvious to the eye.

The problem was seen during testing of the "projected" centers, that puts the center at the surface of largely curved meshes.
Then the shift became apparent, as some arrows were "floating".

![L3left_mirror_issue_seen_after_projection](https://user-images.githubusercontent.com/6583181/99960683-71558200-2d8d-11eb-9434-5ecdd98818e1.png)

A fix is already done and will be commited BEFORE the projected center commit to separate the 2 problems.

**Comment by rhaschke** [comment]
Closed via #11. @guihomework, see [this github doc](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to learn how to automatically link a PR to a previous issue (which then gets closed automatically with the merged PR).

**Comment by guihomework** [comment]
So I need to remember to use _resolve_ instead of _solve_. But I like to have control or what I close or not. Automatic is not good for me.
